version: "3"

services:
  lamp:
    image: mattrayner/lamp:latest-1804
    build:
      context: ./docker
    volumes:
      - ./src/:/var/www/html
    ports:
      - 80:80
      - 443:443
    command: sh /var/www/html/run.sh 127.0.0.1